FROM centos:7

RUN rm -f /etc/yum.repos.d/* \
  && curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo \
  && sed -i '/aliyuncs.com/d' /etc/yum.repos.d/CentOS-Base.repo \
  && yum clean all \
  && yum makecache

RUN yum -y install https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN yum update -y \
    && yum install -y \
    gcc \
    gcc-c++ \
    openssl \
    openssl-devel \
    openssh-server \
    supervisor \
    curl git nginx 

RUN yum install -y --nogpgcheck \
      php72w \
      php72w-fpm \
      php72w-cli \
      php72w-common \
      php72w-opcache \
      php72w-mysql \
      php72w-mbstring \
      php72w-xml \
      php72w-gd \
      php72w-pdo \
      php72w-devel \
    && yum clean all && yum history new

ADD supervisord.ini /etc/supervisord.d/

RUN curl -sS https://getcomposer.org/installer | php \
    && mv /composer.phar /usr/bin/composer \
    && chmod +x /usr/bin/composer

ARG COMPOSER_REPO_PACKAGIST
ENV COMPOSER_REPO_PACKAGIST ${COMPOSER_REPO_PACKAGIST}

RUN if [ ${COMPOSER_REPO_PACKAGIST} ]; then \
  composer config -g repo.packagist composer ${COMPOSER_REPO_PACKAGIST} \
  ;fi

RUN composer global require "hirak/prestissimo";

RUN ssh-keygen -A

RUN sed -i 's/#PasswordAuthentication\ yes/PasswordAuthentication\ no/' /etc/ssh/sshd_config; \
    sed -i 's/#ChallengeResponseAuthentication\ yes/ChallengeResponseAuthentication\ no/' /etc/ssh/sshd_config;

COPY insecure_id_rsa /tmp/id_rsa
COPY insecure_id_rsa.pub /tmp/id_rsa.pub

RUN mkdir /root/.ssh; \
    cat /tmp/id_rsa.pub >> ~/.ssh/authorized_keys; \
    cat /tmp/id_rsa.pub >> ~/.ssh/id_rsa.pub; \
    cat /tmp/id_rsa >> ~/.ssh/id_rsa; \
    rm -f /tmp/id_rsa*; \
    chmod 600 ~/.ssh/authorized_keys ~/.ssh/id_rsa.pub; \
    chmod 400 ~/.ssh/id_rsa;

ADD swoole-src-4.3.3.tar.gz /tmp/

RUN cd /tmp; \
    tar zxvf swoole-src-4.3.3.tar.gz; \
    cd swoole-src-4.3.3; \
    phpize; \
    ./configure  --enable-openssl; \
    make && make install

RUN touch /etc/php.d/swoole.ini; \
    echo 'extension=swoole.so' > /usr/local/etc/php/conf.d/swoole.ini

EXPOSE 22 80

WORKDIR /var/www/

CMD ["supervisord"]