version: "3"

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  php-syncs:
    external: 
      name: 'php-syncs'

services:
  php:
    image: phpenv
    container_name: phpenv
    # deploy:
    #   resources:
    #     limits:
    #       memory: 250M

    mem_limit: 250M
    build:
      context: ./phpenv
      args:
        - COMPOSER_REPO_PACKAGIST=${COMPOSER_REPO_PACKAGIST}
    volumes:
      - ./phpenv/nginx-conf.d:/etc/nginx/conf.d
      - php-syncs:/var/www/
    ports:
      - "${SSH_PORT}:22"
      - "${HTTP_PORT}:80"
    tty: true
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    networks:
      - backend

  mariadb:
    image: mariadb
    container_name: mariadb
    mem_limit: 128M
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    mem_limit: 50M
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend    

